language: java

dist: xenial

jdk: openjdk11

services: xvfb

addons:
  sonarcloud:
    organization: "sreeunifi"
    token:
      secure: $SONAR_TOKEN

install: true


after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sreeUNIFI_ATAT