language: java

dist: xenial

jdk: openjdk11

services: xvfb

addons:
  sonarcloud:
    organization: "sreeunifi"


install: true


after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2


script:
  - mvn clean jacoco:report install sonar:sonar -Dsonar.login=e9f7d9811fed5ab56cdf6eb2e28de483b465f587